### ISSUE TITLE
[Disscusion] how to write test code

### ISSUE THREAD

**Issue by lsh23** [express-helper/express-helper#14]
## Testing Approach
The reason for using decorators is to add or modify the behavior of classes, methods, parameters, and more according to the user's intentions. Therefore, it seems necessary to verify whether the behavior has been changed as intended.

Considering this, how about using end-to-end (e2e) tests to validate the behavior?

In the Node.js environment, you can use a library like "supertest" to perform e2e tests on an Express app.

exmaple test code
```js
//  testApp.ts
export const app: Express = express();
app.use('/', expressHelper());
app.use(expressHelperEndpoint());
```

```js
// Controller for test
@RestController()
export class TestController {
  @Head('/api/test')
  head(@Req() req: Request, @Res() res: Response) {
    res.setHeader('test', 'test');
  }
}
```

```js
// test code
import request from 'supertest'
import app from '../testApp'

describe('HTTP Method Test', () => {
  it('head', async () => {
    const res = await request(app)
      .head('/api/test')

    expect(res.header).toHaveProperty('test');
  })
})
```

**Comment by Dltmd202** [comment]
Oh! There's something called `supertest`!
Yes, this is definitely the right way to test
