### ISSUE TITLE
[Feature] 테스트 환경 구성하기

### ISSUE THREAD

**Issue by Dltmd202** [express-helper/express-helper#7]
## 기능 상세

- [ ] 테스트 환경을 구성해 `npm test`로 테스트 코드를 실행할 수 있는 환경 구성
- [ ] 간단한 예시 테스트 코드 등록해놓기

**Comment by Dltmd202** [comment]
@lsh23  저희 테스트 환경 jest로 하면 될까요?

**Comment by lsh23** [comment]
@Dltmd202 네, jest로 하면 좋을 것 같습니다.
